#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"
ENV['RAILS_ENV'] = ARGV.first || ENV['RAILS_ENV'] || 'development'
require File.expand_path(File.dirname(__FILE__) + "/../config/environment")

Mailman.config.pop3 = {
  username: ENV["GMAIL_USERNAME"],
  password: ENV["GMAIL_PASSWORD"],
  :server   => 'pop.gmail.com',
  :port     => 995,
  :ssl      => true
}

Mailman::Application.run do
  default do
    Email.receive_email(message)
  end
end
