#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"

Mailman::Application.run do
  default do
    Email.create! subject: message.subject, body: message.body.decoded, from: message.from.first, to: message.from.first, date: message.date
  end
end
