#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"

Mailman.config.pop3 = {
  username: ENV["GMAIL_USERNAME"],
  password: ENV["GMAIL_PASSWORD"],
  :server   => 'pop.gmail.com',
  :port     => 995,
  :ssl      => true
}

Mailman::Application.run do
  default do
    Email.receive_email(message)
  end
end
